### ISSUE TITLE
CSS Conflicts

### ISSUE THREAD

**Issue by cristianurbano** [MacKentoch/easyFormGenerator#49]
Hello!

The css causes general conflicts if we add the easyFormGenerator inside another app, because it overrides general html elements and bootstrap classes.

Can you add a class like `easyFormGenerator` and add all CSS sentences inside it, in order to avoid general conflicts? like:
```css
.easyFormGenerator .container {
    padding-left: 0;
    padding-right: 0;
}
```
And if you need some css for the demo page, you can put them inside the same html only for the demo.

I have solved this avoiding adding the css file, but now in the v2.0.0 the css is automatically added as a <style>, **for the moment it would be great if you add a config to off this**, like:

`easyFormSteWayConfigProvider.addCSS(false);`

Thanks!

**Comment by MacKentoch** [comment]
Hi @cristianurbano,

You are right. I did not anticipate that.
The main reason I included css in the bundle to help: it avoids to manually import css + js.
But in that case it does not help...

**Thanks for pointing this issue I will fix that soon.**

I'm not a css super star but adding `!important` should work (*I believe it works so tell me if i'm wrong again* 😄 ). 
In your css it should be a less anoying tempory fix:
```css
// your css
.container {
    padding-left: 20% !important;
    padding-right: 20% !important;
}
```
